# Generated by Django 5.0.2 on 2024-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_timeclock_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='max_employees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
