# Generated by Django 5.0.2 on 2024-02-26 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shift_end_time_alter_shift_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='department',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='location',
        ),
        migrations.AddField(
            model_name='schedule',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
            preserve_default=False,
        ),
    ]
