# Generated by Django 5.0.2 on 2024-02-26 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_shift_department_remove_shift_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='organizaiton',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
            preserve_default=False,
        ),
    ]
