# Generated by Django 5.0.2 on 2024-02-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shift_organizaiton'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
