# Generated by Django 5.0.2 on 2024-02-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shift_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
