# Generated by Django 5.0.2 on 2024-02-26 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_organizaiton_shift_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeclock',
            name='shift',
        ),
        migrations.AddField(
            model_name='timeclock',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.schedule'),
            preserve_default=False,
        ),
    ]
