# Generated by Django 5.0.2 on 2024-02-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_timeclock_shift_timeclock_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='total_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
